### ISSUE TITLE
Test failures out-of-the-box

### ISSUE THREAD

**Issue by fcooper8472** [QuEST-Kit/QuEST#174]
On Ubuntu 19.04 I get a test failure out-of-the-box while following the quick start in the README.

CMake output:
```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GPU acceleration is OFF
-- OMP acceleration is ON
-- MPI distribution is OFF
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Compiling tutorial_example.c to executable demo
-- Found PythonInterp: /usr/local/bin/python3.4 (found version "3.4.9") 
-- Testing is ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fergus/GitRepos/QuEST/build
```

Test output:
```
fergus@fergus:~/GitRepos/QuEST/build$ make test
Running tests...
Test project /home/fergus/GitRepos/QuEST/build
    Start 1: build
1/2 Test #1: build ............................   Passed    1.13 sec
    Start 2: unit
2/2 Test #2: unit .............................***Failed  Error regular expression found in output. Regex=[Error]  0.03 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   1.16 sec

The following tests FAILED:
	  2 - unit (Failed)
Errors while running CTest
make: *** [Makefile:73: test] Error 8
```

I cannot immediately see how to get a more verbose output to pin down what exactly is failing.

**Comment by oerc0122** [comment]
Have you got an error log file created? That should say which test failed. If not, try to run ctest -V and show me what it says.

**Comment by fcooper8472** [comment]
```
test 2
    Start 2: unit

2: Test command: /usr/local/bin/python3.4 "-m" "QuESTTest" "-Q" "/home/fergus/GitRepos/QuEST/build/QuEST" "-l" "/home/fergus/GitRepos/QuEST/build/QuESTLog.log" "unit"
2: Test timeout computed to be: 10000000
2: Traceback (most recent call last):
2:   File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
2:     "__main__", mod_spec)
2:   File "/usr/local/lib/python3.4/runpy.py", line 85, in _run_code
2:     exec(code, run_globals)
2:   File "/home/fergus/GitRepos/QuEST/utilities/QuESTTest/__main__.py", line 35, in <module>
2:     from QuESTTest.QuESTCore import *
2:   File "/home/fergus/GitRepos/QuEST/utilities/QuESTTest/QuESTCore.py", line 269
2:     if self._printToScreen and root: print(*out, **kwargs, flush=True)
2:                                                          ^
2: SyntaxError: invalid syntax
2/2 Test #2: unit .............................***Failed  Error regular expression found in output. Regex=[Error]  0.08 sec
```

**Comment by oerc0122** [comment]
Hmmm... apparently that unpacking style was added in PEP 448 (Python 3.5) will fix it, for now, you can just switch that line to:
 if test1 and test2: print(*out, flush=True, **kwargs)

**Comment by fcooper8472** [comment]
Ok, thanks.  Alternatively could consider turning off Python 3.4 support, as that version has reached [end of life](https://www.python.org/downloads/release/python-3410/).

**Comment by oerc0122** [comment]
Enough HPC machines (see: Archer) still have Python 3.4 as their default that I don't want to drop it just yet.

**Comment by fcooper8472** [comment]
Confirmed that that fix (and using newer python) resolves the issue.
