### ISSUE TITLE
Testing on macOS

### ISSUE THREAD

**Issue by fcooper8472** [QuEST-Kit/QuEST#180]
As part of my working getting a CI system running, the first stage is to have tests running on cloud infrastructure for serial & OpenMP on Linux, macOS and Windows.

I have a [fork of QuEST here](https://github.com/OxfordRSE/QuEST), which is running an [Azure Pipeline on each commit here](https://dev.azure.com/QuEST-Kit/QuEST/_build?definitionId=1).

The pipeline is currently building QuEST libraries fine on Ubuntu 18.04, Ubuntu 16.04, macOS 10.14 and macOS 10.13.

But, on macOS it currently falls over at the testing step.  Here is the relevant output:

Build:
```
[command]/usr/local/bin/cmake --build .
Scanning dependencies of target QuEST
[ 10%] Building C object QuEST/CMakeFiles/QuEST.dir/src/QuEST.c.o
[ 20%] Building C object QuEST/CMakeFiles/QuEST.dir/src/QuEST_common.c.o
[ 30%] Building C object QuEST/CMakeFiles/QuEST.dir/src/QuEST_qasm.c.o
[ 40%] Building C object QuEST/CMakeFiles/QuEST.dir/src/QuEST_validation.c.o
[ 50%] Building C object QuEST/CMakeFiles/QuEST.dir/src/mt19937ar.c.o
[ 60%] Building C object QuEST/CMakeFiles/QuEST.dir/src/CPU/QuEST_cpu.c.o
[ 70%] Building C object QuEST/CMakeFiles/QuEST.dir/src/CPU/QuEST_cpu_local.c.o
[ 80%] Linking C shared library libQuEST.dylib
[ 80%] Built target QuEST
Scanning dependencies of target demo
[ 90%] Building C object CMakeFiles/demo.dir/tutorial_example.c.o
[100%] Linking C executable demo
[100%] Built target demo
```

Test:
```
2: Test command: /Users/vsts/hostedtoolcache/Python/3.5.7/x64/bin/python3.5 "-m" "QuESTTest" "-Q" "/Users/vsts/agent/2.158.0/work/1/s/build/QuEST" "-l" "/Users/vsts/agent/2.158.0/work/1/s/build/QuESTLog.log" "unit"
2: Test timeout computed to be: 10000000
2: Library not found, here's how to redirect QuESTTest to find library:
2: 
2: usage: __main__.py [-Q QUESTPATH]
2: 
2: optional arguments:
2:   -Q QUESTPATH, --questpath QUESTPATH
2:                         Define alternative QuEST library location. The library
2:                         must be named 'libQuEST.so' located in the specified
2:                         directory to be found. Default=../build/QuEST
2: 
2: Traceback (most recent call last):
2:   File "/Users/vsts/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/runpy.py", line 193, in _run_module_as_main
2:     "__main__", mod_spec)
2:   File "/Users/vsts/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/runpy.py", line 85, in _run_code
2:     exec(code, run_globals)
2:   File "/Users/vsts/agent/2.158.0/work/1/s/utilities/QuESTTest/__main__.py", line 32, in <module>
2:     init_QuESTLib(QuESTPath[0].questpath)
2:   File "/Users/vsts/agent/2.158.0/work/1/s/utilities/QuESTPy/QuESTBase.py", line 13, in init_QuESTLib
2:     raise FileNotFoundError(fnfWarning.format(QuESTPath))
2: FileNotFoundError: File /Users/vsts/agent/2.158.0/work/1/s/build/QuEST/libQuEST.so not found 
2: 
2/2 Test #2: unit .............................***Failed  Error regular expression found in output. Regex=[Error]  0.11 sec
```

Unfortunately I don't have a mac to test anything locally - but I know that people on the QuEST project do use it with a mac, so hopefully someone will know how to proceed!

**Comment by fcooper8472** [comment]
I haven't figured out yet what the testing system does with the `.so` file, but it looks as though the testing framework expects the directory that it's in, after the `-Q` flag.

Why not pass the actual library rather than the directory it's in?  CMake knows that information, so can for instance pass `$<TARGET_FILE:QuEST>` rather than `${QuEST_LIB_PATH}`.

On Linux, at least, this resolves to
```
/path/to/build/QuEST/libQuEST.so
```

**Comment by fcooper8472** [comment]
Confirmed: on macOS, `$<TARGET_FILE:QuEST>` resolves to `/path/to/build/QuEST/libQuEST.dylib`.

Getting a different error on windows, though:
```
1: Test command: NOT_AVAILABLE
Test not available without configuration.  (Missing "-C <config>"?)
1/2 Test #1: build ............................***Not Run   0.00 sec
test 2
Test not available without configuration.  (Missing "-C <config>"?)
    Start 2: unit

2: Test command: NOT_AVAILABLE
2/2 Test #2: unit .............................***Not Run   0.00 sec
```

Any ideas on that front?

In terms of a minimal fix for the library names, see [this commit](https://github.com/OxfordRSE/QuEST/commit/128a194a9cc74b68d2fe8e305ca52ce7a29cb2ce): but essentially just passing in the actual library rather than the directory it's in is sufficient.
